/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SampleCI;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.Platform;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.annotations.Test;

import com.perfecto.reportium.client.ReportiumClient;
import com.perfecto.reportium.client.ReportiumClientFactory;
import com.perfecto.reportium.model.Job;
import com.perfecto.reportium.model.PerfectoExecutionContext;
import com.perfecto.reportium.model.Project;
import com.perfecto.reportium.test.TestContext;
import com.perfecto.reportium.test.result.TestResult;
import com.perfecto.reportium.test.result.TestResultFactory;


public class PerfectoSelenium {

	@Test
	public void main() throws MalformedURLException {
		//Update cloudName variable with your perfecto cloud name
		String cloudName = System.getProperty("cloudName");
		//Update securityToken variable with your perfecto security token. 
		//String securityToken = System.getProperty("securityToken");
		String securityToken = "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI4YmI4YmZmZS1kMzBjLTQ2MjctYmMxMS0zNTYyMmY1ZDkyMGYifQ.eyJpYXQiOjE2MjM2ODI1ODUsImp0aSI6ImUzZmJlOTc4LTRiZGUtNGNlYy05MzlkLWViOGY2YmUxMTg0OSIsImlzcyI6Imh0dHBzOi8vYXV0aC5wZXJmZWN0b21vYmlsZS5jb20vYXV0aC9yZWFsbXMvZGVtby1wZXJmZWN0b21vYmlsZS1jb20iLCJhdWQiOiJodHRwczovL2F1dGgucGVyZmVjdG9tb2JpbGUuY29tL2F1dGgvcmVhbG1zL2RlbW8tcGVyZmVjdG9tb2JpbGUtY29tIiwic3ViIjoiZWI3NjM0MGUtNzhmZS00YWY0LWI3NTktYWViNTc0NjUwOTdiIiwidHlwIjoiT2ZmbGluZSIsImF6cCI6Im9mZmxpbmUtdG9rZW4tZ2VuZXJhdG9yIiwibm9uY2UiOiI1NjNiNGE3ZS04ZDAzLTRmNDEtODdmNy0yZDBjZmUxZjEwNWQiLCJzZXNzaW9uX3N0YXRlIjoiNDhlMmMzMmUtYThiNC00YWZlLTk3Y2EtNjJkYTI4NzM3NTFjIiwic2NvcGUiOiJvcGVuaWQgb2ZmbGluZV9hY2Nlc3MifQ.LSP3Oil9jMFG52SaXUfWwXhsZiOhk_1rRIXWArnpLeU";

		String browserName = "mobileOS";
		DesiredCapabilities capabilities = new DesiredCapabilities(browserName, "", Platform.ANY);
		capabilities.setCapability("securityToken", securityToken);
		capabilities.setCapability("platformName", "Android");

		RemoteWebDriver driver = new RemoteWebDriver(new URL("https://" + "demo" + ".perfectomobile.com/nexperience/perfectomobile/wd/hub"), capabilities);
		driver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
		driver.manage().timeouts().pageLoadTimeout(15, TimeUnit.SECONDS);
		// Reporting client. For more details, see http://developers.perfectomobile.com/display/PD/Reporting
		PerfectoExecutionContext perfectoExecutionContext;
//		if(!System.getProperty("jobName").equals("NA")) {
//			perfectoExecutionContext = new PerfectoExecutionContext.PerfectoExecutionContextBuilder()
//					.withProject(new Project("My Project", "1.0"))
//					.withJob(new Job(System.getProperty("jobName") , Integer.parseInt(System.getProperty("jobNumber"))))
//					.withContextTags("tag1")
//					.withWebDriver(driver)
//					.build();
//		} else {
			perfectoExecutionContext = new PerfectoExecutionContext.PerfectoExecutionContextBuilder()
					.withProject(new Project("My Project", "1.0"))
					.withContextTags("tag1")
					.withWebDriver(driver)
					.build();
	//	}
		ReportiumClient reportiumClient = new ReportiumClientFactory().createPerfectoReportiumClient(perfectoExecutionContext);

		try {
			reportiumClient.testStart("Perfecto mobile web test", new TestContext("tag2", "tag3"));
			reportiumClient.stepStart("browser navigate to perfecto");
			driver.get("https://www.perfecto.io");
			reportiumClient.stepEnd();

			reportiumClient.stepStart("Verify title");
			String aTitle = driver.getTitle();
			System.out.println(aTitle);
			//compare the actual title with the expected title
			if (!aTitle.equals("Web & Mobile App Testing | Continuous Testing | Perfecto"))
				throw new RuntimeException("Title is mismatched");
			reportiumClient.stepEnd();

			//STOP TEST
			TestResult testResult = TestResultFactory.createSuccess();
			reportiumClient.testStop(testResult);

		} catch (Exception e) {
			TestResult testResult = TestResultFactory.createFailure(e);
			reportiumClient.testStop(testResult);
			e.printStackTrace();
		} finally {
			driver.close();
			driver.quit();
			// Retrieve the URL to the DigitalZoom Report 
			String reportURL = reportiumClient.getReportUrl();
			System.out.println(reportURL);
		}
	}
}
